name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIR: .
      FILE: cv
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Build LaTeX file
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE }}
          working_directory: ${{ env.DIR }}

      - name: Move generated PDF
        run: |
          mkdir -p github_artifacts
          mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts/cv.pdf
